language: android
android:
    components:
        # Update Android SDK Tools
        - tools
        - build-tools-23.0.2
        - android-23

        # SUpport Library
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-support
        - extra-android-m2repository

        # Running Image
        - sys-img-armeabi-v7a-android-22
script:
    - ./gradlew build

env:
    global:
        - ADB_INSTALL_TIMEOUT=8

before_script:
    - android-wait-for-emulator
